/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      boxShadow: {
        low: "10px 22px 20px -6px rgba(0, 0, 0, 0.04)",
        lows: "5px 5px 8px -6px rgba(0, 0, 0, 0.04)",
      },
    },
    screens: {
      ms: "100px",
      xs: "320px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
      "3xl": "1920px",
      "4xl": "2880px",
    },
    colors: {
      primary: "#F8A933",
      "primary-mid": "#FFD28F",
      "primary-low": "#FFEFD8",
      secondary: "#44A5FF",
      "secondary-mid": "#AADBFF",
      "secondary-low": "#E4F4FF",
      "secondary-lows": "#EDF7FF",
      border: "#EEEEEE",
      success: "#29EC3D",
      "success-mid": "#29EC3D",
      "success-low": "#EDFFEF",
      error: "#E15454",
      "error-mid": "#E15454",
      "error-low": "#FFEBEB",
      black: "#000000",
      greydark: "#404040",
      green: "#52C41A",
      greens: "#19DD2C",
      org: "#F67704",
      prpl: "#9A4AFF",
      body: "#4F4F4F",
      label: "#868686",
      placeholder: "#CACACA",
      line: "#EDEDED",
      bg: "#F8F8F8",
      white: "#FFFFFF",
      redRefresh: "#E70000",
      orgblur: "#FFF4EA",
      mn: "#00008B",
    },
    fontSize: {
      "2xs": ["0.5625rem", { lineHeight: "1rem", letterSpacing: "0.25px" }],
      xs: ["0.8125rem", { lineHeight: "20px", letterSpacing: "0.25px" }],
      sm: ["0.875rem", { lineHeight: "20px", letterSpacing: "0.75px" }],
      s: ["0.9375rem", { lineHeight: "24px", letterSpacing: "0.75px" }],
      base: ["1rem", { lineHeight: "24px", letterSpacing: "0.75px" }],
      m: ["1.125rem", { lineHeight: "32px", letterSpacing: "0.75px" }],
      l: ["1.25rem", { lineHeight: "32px", letterSpacing: "0.75px" }],
      lg: ["1.375rem", { lineHeight: "32px", letterSpacing: "0.75px" }],
      xl: ["1.5rem", { lineHeight: "32px", letterSpacing: "1px" }],
      "2xl": ["2rem", { lineHeight: "48px", letterSpacing: "1px" }],
      "3xl": ["3rem", { lineHeight: "56px", letterSpacing: "1px" }],
      "4xl": ["3.5rem", { lineHeight: "72px", letterSpacing: "1px" }],
      "5xl": ["4rem", { lineHeight: "88px", letterSpacing: "1px" }],
    },
  },
  plugins: [],
};
